function [] = EOMplotter(Tout,State_out2)
    %This function is only used as  a plotting tool for the different
    %components of the state vector and the equation of motions

    figure(1)
    subplot(3,1,1)
        plot(Tout, State_out2(:,1))
        xlabel('Time(s)')
        ylabel('x[m]')
        ylim([-1 1])
    subplot(3,1,2)
        plot(Tout, State_out2(:,2))
        xlabel('Time(s)')
        ylabel('y[m]')
        %ylim([0 60])
    subplot(3,1,3)
        plot(Tout, State_out2(:,3))
        xlabel('Time(s)')
        ylabel('z[m]')
        %ylim([-1 1])
    sgtitle('Position vs. Time')
    xlim([0 10])

    figure(2)
    subplot(3,1,1)
        plot(Tout, State_out2(:,4))
        xlabel('Time(s)')
        ylabel('Roll[rad]')
    subplot(3,1,2)
        plot(Tout, State_out2(:,5))
        xlabel('Time(s)')
        ylabel('Pitch[rad]')
    subplot(3,1,3)
        plot(Tout, State_out2(:,6))
        xlabel('Time(s)')
        ylabel('Yaw[rad]')
    sgtitle('Euler Angles vs. Time')
    %ylim([-1 1])

    figure(3)
    subplot(3,1,1)
        plot(Tout, State_out2(:,7))
        xlabel('Time(s)')
        ylabel('uE[m/s]')
        %ylim([-1 1])
    subplot(3,1,2)
        plot(Tout, State_out2(:,8))
        xlabel('Time(s)')
        ylabel('vE[m/s]')
        %ylim([3 8])
    subplot(3,1,3)
        plot(Tout, State_out2(:,9))
        xlabel('Time(s)')
        ylabel('wE[m/s]')
        %ylim([-1 1])
    sgtitle('Velocity vs. Time') 

    figure(4)
    subplot(3,1,1)
        plot(Tout, State_out2(:,10))
        xlabel('Time(s)')
        ylabel('p[rad/s]')
    subplot(3,1,2)
        plot(Tout, State_out2(:,11))
        xlabel('Time(s)')
        ylabel('q[rad/s]')
    subplot(3,1,3)
        plot(Tout, State_out2(:,12))
        xlabel('Time(s)')
        ylabel('r[rad/s]')
    sgtitle('Angular Velocity vs. Time')
    %ylim([-1 1])
    
    end

